#require(File.join(File.dirname(__FILE__), "tenpin/**/*"))
require("models/score")
require("models/game")
require("models/frame")
require("models/player")
require("printers/row_printer")
require("printers/base_report_printer")
require("printers/text_game_printer")
require("printers/text_player_printer")
require("printers/advance_game_printer")